#!/bin/bash
input1="$1"

main() {
    case $input1 in
        start)
            current_script_pid=$$
            pids=$(pidof S15_z_auto_fwupdate)
            IFS=' ' read -r -a pid_array <<< "$pids"  # Added '<<<' to fix array assignment
            for pid in "${pid_array[@]}"; do
                if [ "$pid" != "$current_script_pid" ]; then  # Added double quotes for variable expansion
                    kill "$pid"
                fi
            done
            ;;
        stop)
            killall S15_z_auto_fwupdate
            exit 0
            ;;
        *)
            echo "Usage $0 (start|stop)"
            echo "start - starts the background process for automatic firmware upgrade"
            echo "stop - stops the background process, but not the fwupdate service"
            exit 1
            ;;
    esac

    WAGO_FWUPDATE="/etc/config-tools/fwupdate"
    while true; do
        CURRENT_FWUPDATE_STATUS=$($WAGO_FWUPDATE status | grep status= | awk -F'=' '{print $2}')
        case $CURRENT_FWUPDATE_STATUS in
            inactive)
                $WAGO_FWUPDATE activate &>/dev/null
                ;;
            prepared)
                mv /tmp/FW.raucb /tmp/fwupdate/FW.raucb
                $WAGO_FWUPDATE start -q --path /tmp/fwupdate &>/dev/null
                ;;
            unconfirmed)
                $WAGO_FWUPDATE finish &>/dev/null
                ;;
            errorfinished)
                $WAGO_FWUPDATE clear &>/dev/null
                rm /etc/rc.d/S15_z_auto_fwupdate -f
                exit 0
                ;;
        esac
        sleep 10
    done
}

main